name: Remove untagged images from registry

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  PACKAGE_NAME: docker-event-monitor

jobs:
  Delete_untagged_images:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Delete all images from repository without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4.0.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: ${{ env.PACKAGE_NAME }}
          untagged_only: true
          owner_type: user
          except_untagged_multiplatform: true
