name: Sync Back to Development

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  sync-branches:
    # The job needs to be able to pull the code and create a pull request.
    permissions:
      contents: read #  for actions/checkout
      pull-requests: write #  to create pull request

    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Opening pull request
        run: gh pr create -B development -H main --title 'Sync main back into development' --body 'Created by Github action' --label 'internal'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
